### PR TITLE
maps + edit address + contact number

### PR DESCRIPTION
**Pull request by ownin0**

### CODE REVIEW

**Review by otaKenneth — COMMENTED** [review]
Need to add maps to vendor registration form too with element name="lat"&"long"

**Comment by otaKenneth** [comment]
add latitude and longitude field, when clicked on map. it will be reflected as well

**Comment by otaKenneth** [comment]
combine first_name and last_name fields to one. name field

**Comment by ownin0** [comment]
done. pa check. yung sa map waiting pa sa google account for API map pin

**Review by otaKenneth — APPROVED** [review]

**Pull request merged**
